[[cuPDLPx]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "7279e30e6d44a54f9691fc9acdf20382dcf3e037"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "4a359f378bc94edf61255c68720d2fe671da9e174d93335715f5f6884f60a32a"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+0/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "78ca6463b48d9d9ad86fc5fd06debb9ed6b9e3cf"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "19aa9746c86c4d4a66a967cac4c75816653ea565d85233e9b77ce41e65267736"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+0/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "30d2d71930ffa7c4ec7764cc33d5c028838668da"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "90cc7d208d5b7d59ea0755db1419b3777e4e54ef4b3605651682d71fc0ae8f95"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+0/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+12.6.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "01bc6673374edb5e976d03cf9c72fed3cd98b254"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "a6273f843b0af167a7148f3a7618b843cb5e38687e27a1316db4a4b96acde524"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+0/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+12.8.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.9"
git-tree-sha1 = "993e14ba930bc9dd8cd663e574c132c89e2192f9"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "e0f1b4aca80e0bd5712f3bc851b98bb459ba10c152b3ff7c5e299a9062b50eb2"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+0/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+12.9.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "17aa926a90c6cbdc482f1737a82ffd6b7beb888a"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "97fbc8ebf4961e6488198bafe5bde17d9a92142e5c8667a1b719a2dc7a49227f"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+0/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+13.0.tar.gz"
