[[cuPDLPx]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "4d407e51174c3bfe2f138e6e1db2531d0bc6240d"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "c9f3baabeb6e0ffa694625423804c572f5ba56ca6099ee77e7c8cb043e7eea4b"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "2d38c014febbeaea16dfa3afaf0783a548e9f659"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "86d4817823ee0ac587be58f942bdd19367a314022b42ab0a036c3b544734522a"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "4b0b91d466b7b202fe9ede92e9b7488c9a90df35"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "ee8c6db4ac29391b5c244ca22b1fab0af32cffa4977afd7a237b1dc56f74434c"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.6.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "08fccad637d5cede858e00a1aa8c3ba9ebbbb5d0"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "29746463af12662cf9d62049139c568292eb52b3293d4f3ab3b8d652b080ef42"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.8.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.9"
git-tree-sha1 = "0f836eb0299e5d9ffb2be437abf314ca3bb40e8e"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "215adebc04a71dba6087cbb67a88111b68fbe5a8cf129b558b5c8ce865679563"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.9.tar.gz"
