[[cuPDLPx]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "651a97fdac48b22ab3480fac655a05a5013d62a4"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "92f02907e91d9f981dd41d60b2b8bd179abb285cf141560839897937b1b6e959"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.5+0/cuPDLPx.v0.2.5.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "649ca598fefa20b1e0319948f3722e228ceb60a5"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "fc39e1c32d681d9a6803c5dbedbe2858b2d95e998b2fa2997b51d43b69c214a7"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.5+0/cuPDLPx.v0.2.5.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "c561b785539e7c6e194b81ba7ef3ea3cc4466a3f"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "3b2b8ab36917f5c337ebf2cadf2e46e57e0f885eeb297041ae8235c7d269c74f"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.5+0/cuPDLPx.v0.2.5.x86_64-linux-gnu-cuda+12.6.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "64dbf5f76a64c7c099cf98e88ea9c458297a890e"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "5236265faa8afd14a74a9620f808dc86cefdc0ecdabe5c459af272590986215d"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.5+0/cuPDLPx.v0.2.5.x86_64-linux-gnu-cuda+12.8.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.9"
git-tree-sha1 = "052a02918fa82375122e0271af40ef93576a63eb"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "a636c60839a20afb737060328afc3586ea9d3ca3347014354da388c9d8396990"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.5+0/cuPDLPx.v0.2.5.x86_64-linux-gnu-cuda+12.9.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "26ba61ab4e3ce90990b9d6f983decf8a8dec0834"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "4f8cc54d7aaf2b01b88d30ac6c8e2ddea7235ac1d7cdf25ea7a766e8208598bb"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.5+0/cuPDLPx.v0.2.5.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "13.1"
git-tree-sha1 = "82a56c2b04bc52ef1a4ee83f5c11377d3a28bb1d"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "1e536ab9ce4fa88dede3489a937588f53f6252000dbea276abfe491f308658cb"
    url = "https://github.com/JuliaBinaryWrappers/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.5+0/cuPDLPx.v0.2.5.x86_64-linux-gnu-cuda+13.1.tar.gz"
